CREATE TABLE CUSTOMER (
     ID  SERIAL PRIMARY KEY,
     SCHEMA_NAME varchar(63) NOT NULL,
     COMPANY_NAME varchar(100) NOT NULL,
     TRADE_NAME varchar(100) NOT NULL,
     EMAIL varchar(100) NOT NULL,
     CNPJ varchar(14) NOT NULL,
     CITY_ID INT NOT NULL,
     CEP VARCHAR(8) NOT NULL,
     ADDRESS varchar(100) NOT NULL,
     ADDRESS_NUMBER varchar(50) NOT NULL,
     DISTRICT varchar(100) NOT NULL,
     COMPLEMENT varchar(200) NULL,
     PHONE_NUMBER varchar(15) NOT NULL,
     ACTIVE BOOLEAN DEFAULT TRUE,
     CONSTRAINT FK_CUSTOMER_CITY FOREIGN KEY(CITY_ID) REFERENCES public.CITY(ID)
);
