apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluyt
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluyt
  namespace: default
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluyt
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluyt
subjects:
  - kind: ServiceAccount
    name: fluyt
    namespace: default
# kubectl get secret $(kubectl get serviceaccounts fluyt -o jsonpath="{.secrets[0].name}") -o jsonpath="{.data.token}"  |base64 -d
