version: '3'
services:

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    volumes:
      - ~/Documentos/docker/postgres_fluyt_data:/var/lib/postgresql/data
    env_file:
      - ./app-postgres.env
    ports:
      - 5432:5432
    expose:
      - 5432

  keycloak:
    image: gasparbarancelli/keycloak:19.0.1
    container_name: keycloak
    restart: unless-stopped
    env_file:
      - ./keycloak-postgres.env
    entrypoint: [ "/opt/keycloak/bin/kc.sh", "start-dev", "--auto-build", "--db=postgres"]
    expose:
      - 18080
    ports:
      - 18080:8080
    depends_on:
      - postgres
      
volumes:
  postgres_data:
#    name: keycloak_postgres_data
    driver: local
