version: '3'
services:

  postgres-app:
    image: postgres:latest
    container_name: postgres-app
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./app-postgres.env
    ports:
      - 5432:5432
    expose:
      - 5432
      
volumes:
  postgres_data:
    name: keycloak_postgres_data
    driver: local
