CREATE TABLE COMPANY (
    ID SERIAL PRIMARY KEY,
    COMPANY_NAME bpchar(100) NOT NULL,
    TRADE_NAME bpchar(100) NOT NULL,
    CNPJ bpchar(14) NOT NULL,
    CITY_ID INT NOT NULL,
    ZIP_CODE bpchar(8) NULL,
    ADDRESS bpchar(100) NOT NULL,
    ADDRESS_NUMBER bpchar(50) NOT NULL,
    DISTRICT bpchar(100) NOT NULL,
    COMPLEMENT bpchar(200) NULL,
    PHONE_NUMBER bpchar(15) NOT NULL,
    EMAIL bpchar(100) NOT NULL,
    STATE_REGISTER bpchar(9) NOT NULL,
    MUNICIPAL_REGISTER bpchar(11) NOT NULL,
    CONSTRAINT FK_FILIAL_CITY FOREIGN KEY(CITY_ID) REFERENCES public.CITY(ID)
);