CREATE TABLE PERSON (
      ID  SERIAL PRIMARY KEY,
      NAME VARCHAR(100) NOT NULL,
      CPF_CNPJ VARCHAR(14) NOT NULL,
      PHONE_NUMBER VARCHAR(15) NOT NULL,
      EMAIL VARCHAR(100) NOT NULL,
      TYPE VARCHAR(20) NOT NULL,
      CITY_ID INT,
      ADDRESS VARCHAR(100),
      ADDRESS_NUMBER VARCHAR(50),
      DISTRICT VARCHAR(100),
      COMPLEMENT VARCHAR(200),
      ZIP_CODE VARCHAR(8),
      REFERENCE_POINT VARCHAR(100),
      CONSTRAINT FK_CUSTOMER_CITY FOREIGN KEY(CITY_ID) REFERENCES public.CITY(ID),
      CONSTRAINT UQ_PERSON_CPF_CNPJ UNIQUE (CPF_CNPJ)
);
