# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

  test:
    runs-on: ubuntu-latest
    name: Tests
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run unit tests
        run: mvn -B test --file pom.xml

  delivery:
    runs-on: ubuntu-latest
    name: Deliver
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build Project, create docker image and send image to dockerhub
        env:
          QUARKUS_CONTAINER_IMAGE_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          QUARKUS_CONTAINER_IMAGE_PASSWORD: ${{secrets.DOCKERHUB_TOKEN}}
          QUARKUS_CONTAINER_IMAGE_PUSH: true
          QUARKUS_CONTAINER_IMAGE_GROUP: gasparbarancelli
          QUARKUS_CONTAINER_IMAGE_NAME: restaurante-backend
          QUARKUS_CONTAINER_IMAGE_TAG: ${{github.run_number}}
        run:  mvn -B clean package -Dquarkus.container-image.build=true

  gitops:
    runs-on: ubuntu-latest
    name: Deploy
    needs: delivery
    steps:
      - name: Update gitOps repository
        uses: simplycubed/gitops-update@0.16
        with:
          filename: "apps/restaurante/backend/app.yaml"
          key: "spec.template.spec.containers.0.image"
          value: "gasparbarancelli/restaurante-backend:${{github.run_number}}"
          github-deploy-key: ${{secrets.GITOPS}}
          github-org-and-repo: "fluytcloud/restaurante-infrastructure"